name: Node Continuous Integration

on:
  pull_request:
    branches: [ master ]

jobs:
  test_and_simulate_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '13.9.0' ]
    name: Node ${{ matrix.node }} environment
    steps:
    - name: Code checkout
      uses: actions/checkout@v2.0.0
    - name: Setup Node Environment
      uses: actions/setup-node@v1.4.1
      with:
        node-version: ${{ matrix.node }}
      # Use jaid/action-npm-install to ensure that correct package manager is used for
      # installing dependencies (based of existence yarn.lock/package-lock.json)
    - name: Install dependencies
      uses: jaid/action-npm-install@v1.2.1
    - run: yarn lint
    - run: yarn test
    - run: yarn build
    - uses: tzkhan/pr-update-action@v1.1.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        branch-regex: 'foo-\d+'
        lowercase-branch: false
        title-template: '[%branch%]'
        replace-title: false
        title-prefix-space: true
        uppercase-title: true
        body-template: '[Link to %branch%](https://url/to/browse/ticket/%branch%)'
        replace-body: false
        body-prefix-newline-count: 2
        uppercase-body: true