name: Node Continuous Integration

on:
  pull_request:
    branches: [ master ]

jobs:
  test_and_simulate_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '13.9.0' ]
    name: Node ${{ matrix.node }} environment
    steps:
    - name: Code checkout
      uses: actions/checkout@v2.0.0
    - name: Setup Node Environment
      uses: actions/setup-node@v1.4.1
      with:
        node-version: ${{ matrix.node }}
      # Use jaid/action-npm-install to ensure that correct package manager is used for
      # installing dependencies (based of existence yarn.lock/package-lock.json)
    - name: Install dependencies
      uses: jaid/action-npm-install@v1.2.1
    - run: yarn lint
    - run: yarn test
    - run: yarn build
    - name: Dry run Semantic release
      id: semantic
      uses: cycjimmy/semantic-release-action@latest
      with:
        dry_run: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      if: steps.semantic.outputs.new_release_published == 'true'
      with:
        branch: 'release/${{ steps.semantic.outputs.new_release_version }}'
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore(Version): Prepare v${{ steps.semantic.outputs.new_release_version }}. Merge release/${{ steps.semantic.outputs.new_release_version }} into develop.'
        title: Prepare v${{ steps.semantic.outputs.new_release_version }}
        b