name: Prepare

on:
  push:
    branches: [ develop ]

jobs:
  build_and_prepare_release_from_develop_with_semantic_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '13.9.0' ]
    name: Node@${{ matrix.node }}
    steps:
    - name: Code checkout
      uses: actions/checkout@v2.0.0
    - name: Setup Node@${{ matrix.node }}
      uses: actions/setup-node@v1.4.1
      with:
        node-version: ${{ matrix.node }}
      # Use jaid/action-npm-install to ensure that correct package manager is used for
      # installing dependencies (based of existence yarn.lock/package-lock.json)
    - name: Install dependencies
      uses: jaid/action-npm-install@v1.2.1
    - run: yarn build
    - name: Simulate(dry-run) release with Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v2
      with:
        branch: develop
        dry_run: true
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/exec
          @semantic-release/git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Output simulated release
      run: |
        echo Simulated release of ${{ steps.semantic.outputs.new_release_version }} from develop
        echo Release notes for version ${{ steps.semantic.outputs.new_release_version }}
        echo ${{ steps.semantic.outputs.new_release_notes }}
