name: Prepare

on:
  push:
    branches: [ develop ]

jobs:
  prepare_release_with_dry_run_semantic_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '13.9.0' ]
    name: Node@${{ matrix.node-version }}
    steps:
    - name: Code checkout
      uses: actions/checkout@v2.0.0
    - name: Setup Node@${{ matrix.node-version }}
      uses: actions/setup-node@v1.4.1
      with:
        node-version: ${{ matrix.node-version }}
      # Use jaid/action-npm-install to ensure that correct package manager is used for
      # installing dependencies (based of existence yarn.lock/package-lock.json)
    - name: Install dependencies
      uses: jaid/action-npm-install@v1.2.1
    - run: yarn build
    - name: Simulate(dry-run) release with Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v2
      with:
        branch: master
        dry_run: true
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/exec
          @semantic-release/git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Output simulated release
      run: |
        echo Simulated release of ${{ steps.semantic.outputs.new_release_version }} from develop