name: Release

on:
  push:
    branches: [ master ]


jobs:
  build_and_publish_release_with_semantic_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '13.9.0' ]
    name: Node@${{ matrix.node }}
    steps:
    - name: Code checkout
      uses: actions/checkout@v2.0.0
    - name: Setup Node@${{ matrix.node }}
      uses: actions/setup-node@v1.4.1
      with:
        node-version: ${{ matrix.node }}
      # Use jaid/action-npm-install to ensure that correct package manager is used for
      # installing dependencies (based of existence yarn.lock/package-lock.json)
    - name: Install dependencies
      uses: jaid/action-npm-install@v1.2.1
    - run: yarn build
    - name: Publish with Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      id: semantic   # Need an `id` for output variables
      with:
        # You can specify specifying version range for the extra plugins if you prefer.
        extra_plugins: |
          @semantic-release/changelog@5.0.1
          @semantic-release/git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
