name: Tests
on: push
jobs:
  lint:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        # Use setup-node to define Node's environment version
      - name: Setup Node Environment
        uses: actions/setup-node@v1.4.1
        with:
          node-version: "13.9.0"
        # Use action-npm-install to ensure that correct package manager is used for
        # installing dependencies (based on yarn.lock/package-lock.json)
      - name: Install dependencies
        uses: jaid/action-npm-install@v1.2.1
      - run: yarn test
