name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '13.9.0' ]
    name: Node@${{ matrix.node }}
    steps:
    - name: Code checkout
      uses: actions/checkout@v2.0.0
    - name: Setup Node@${{ matrix.node }}
      uses: actions/setup-node@v1.4.1
      with:
        node-version: ${{ matrix.node }}
      # Use jaid/action-npm-install to ensure that correct package manager is used for
      # installing dependencies (based of existence yarn.lock/package-lock.json)
    - name: Install dependencies
      uses: jaid/action-npm-install@v1.2.1
    - run: yarn test
      env:
        CI: true
    - run: yarn lint
      env:
        CI: true
