name: Test

on: push

env:
  CI: true

jobs:
  # Unit tests with Mocha
  test_unit:
    strategy:
      matrix:
        node-version: [ 13.x, 14.x ]
    name: Unit tests on Node.js@${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        uses: jaid/action-npm-install@v1.2.1
      - run: yarn test:unit
  # Integration tests with Mocha
  test_integration:
    strategy:
      matrix:
        node-version: [ 13.x, 14.x ]
    name: Integration tests on Node.js@${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        uses: jaid/action-npm-install@v1.2.1
      - run: yarn test:integration
  test_lint:
    name: Test linting
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Install dependencies
        uses: jaid/action-npm-install@v1.2.1
      - run: yarn test:lint
  validate_test_coverage:
    name: Validate test coverage
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Install dependencies
        uses: jaid/action-npm-install@v1.2.1
      - run: yarn test:coverage
