name: Test Release

on:
  pull_request:
    branches: [ master ]

jobs:
  test_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
        env:
          CI: true
      - name: Install dependencies
        uses: jaid/action-npm-install@v1.2.1
      - name: Add Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          dry_run: true
          branch: master
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Run Build
        run: yarn run build

      - name: Print Dry Run Semantic Release Version
        run: echo ${{ steps.semantic.outputs.new_release_version }}