name: Tests
on: push
jobs:
  lint:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2.0.0
      - name: actions/setup-node
        uses: actions/setup-node@v1.4.1
        with:
          node-version: "13.9.0"
      - name: dependencies install
        uses: jaid/action-npm-install@v1.2.4"
      - run: yarn test
