name: "Update Pull Request"

on:
  pull_request:
    types: [opened]

jobs:
  format_pr_information:
    runs-on: ubuntu-latest
    name: Format information
    if: >-
      github.actor != 'github-actions[bot]'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Read 'bug' body template
      if: contains(github.event.pull_request.labels.*.name, 'bug')
      id: pull_request_body
      uses: juliangruber/read-file-action@v1
      with:
        path: ./.github/ISSUE_TEMPLATE/bug_template.md
    - name: Read 'fix' body template
      if: contains(github.event.pull_request.labels.*.name, 'fix')
      id: pull_request_body
      uses: juliangruber/read-file-action@v1
      with:
        path: ./.github/ISSUE_TEMPLATE/fix_template.md
    - name: Read 'default' body template
      id: pull_request_body
      uses: juliangruber/read-file-action@v1
      with:
        path: ./.github/ISSUE_TEMPLATE/pull_request_template.md
    - name: Update Pull Request
      uses: tzkhan/pr-update-action@v1.1.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        branch-regex: '[a-z\d-_.\/]+'
        lowercase-branch: true
        title-template: '[%branch%]'
        replace-title: false
        title-prefix-space: true
        uppercase-title: false
        body-template: |
          [Link to %branch%](${{ secrets.TICKET_URL }}%branch%)
          ---
          ${{ steps.pull_request_body.outputs.content }}
        replace-body: false
        body-prefix-newline-count: 2
        uppercase-body: true
    - name: Assign labels
      uses: technote-space/pr-labeler-action@v4
      with:
        CONFIGURATION_PATH: .github/pr-labeler.yml # optional, .github/pr-labeler.yml is the default value